import streamlit as st
from huggingface_hub import InferenceClient
import io
from PIL import Image
from prompt_manager import PromptLibraryManager

# --- STREAMLIT DIALOGS (POP-UPS) ---

@st.dialog("🔐 Secret Prompt Vault")
def show_secret_prompt(prompt_text):
    st.warning("This area is restricted for the Architect.")
    pwd = st.text_input("Enter Master Password:", type="password")
    if st.button("Unlock"):
        if pwd == "turaab786":
            st.success("Access Granted!")
            st.text_area("AI Prompt (Do not share):", value=prompt_text, height=150)
        elif pwd:
            st.error("Access Denied! Incorrect Password.")

@st.dialog("🖼️ Full Resolution View", width="large")
def show_full_image(image_obj):
    # Modal ke andar image full quality aur width me dikhegi
    st.image(image_obj, use_container_width=True)


# --- Setup Inference Client ---
def get_client():
    try:
        token = st.secrets.get("HF_API_TOKEN", st.secrets.get("HF_TOKEN"))
        return InferenceClient(token=token)
    except Exception as e:
        st.error("Secrets file mein HF_API_TOKEN nahi mila!")
        return None

# --- Resilient Image Generation Logic ---
def generate_with_rotation(prompt):
    client = get_client()
    if not client:
        return None, None

    MODEL_POOL = [
        "black-forest-labs/FLUX.1-schnell",
        "stabilityai/stable-diffusion-xl-base-1.0",
        "runwayml/stable-diffusion-v1-5"
    ]

    for model_id in MODEL_POOL:
        try:
            image = client.text_to_image(prompt, model=model_id)
            return image, model_id
        except Exception as e:
            continue
            
    return None, None

# --- MAIN CHATBOT DASHBOARD ---
def run_image_gen():
    
    # 1. Custom CSS: Chat Input ko bottom par zordar tarike se freeze karne ke liye
    st.markdown("""
        <style>
        div[data-testid="stChatInput"] {
            position: fixed !important;
            bottom: 0px !important;
            z-index: 9999 !important;
            padding-bottom: 25px !important;
            width: 700px !important;
        }
        /* Chat ke aakhiri message ke baad jagah chhodne ke liye */
        .main .block-container {
            padding-bottom: 120px !important;
        }
        </style>
    """, unsafe_allow_html=True)

    # 2. Top Bar: Title & Clear Button
    col1, col2 = st.columns([4, 1])
    with col1:
        st.title("🎨 Turaab Vision - Studio")
    with col2:
        if st.button("🧹 Clear Chat"):
            st.session_state.messages = []
            st.rerun()

    st.markdown("---")

    # 3. Memory Initialization
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # 4. Display Chat & Image History
    for i, msg in enumerate(st.session_state.messages):
        with st.chat_message(msg["role"]):
            
            # Agar system/assistant ne text diya hai
            if msg.get("content"):
                st.markdown(msg["content"])
            
            # AI Prompt ka Secret Button
            if "prompt" in msg and msg["prompt"]:
                if st.button("👁️ View Secret Prompt", key=f"btn_prompt_{i}"):
                    show_secret_prompt(msg["prompt"])
            
            # Image Display with UX Buttons
            if "image" in msg and msg["image"] is not None:
                st.markdown("<br>", unsafe_allow_html=True)
                # Fixed 5x7 ratio jaisa thumbnail
                st.image(msg["image"], caption=f"Generated by {msg.get('model', 'Turaab')}", width=400)
                
                # Buttons layout below the image
                btn_col1, btn_col2 = st.columns([1, 1])
                
                with btn_col1:
                    # Full Size Button (Triggers Dialog)
                    if st.button("🔍 View Full Size", key=f"btn_full_{i}"):
                        show_full_image(msg["image"])
                
                with btn_col2:
                    # Download Button
                    buf = io.BytesIO()
                    msg["image"].save(buf, format="PNG")
                    st.download_button(
                        label="📥 Download", 
                        data=buf.getvalue(), 
                        file_name=f"turaab_art_{i}.png", 
                        mime="image/png", 
                        key=f"dl_{i}"
                    )

    # 5. Chat Input (Bottom Freeze)
    if user_idea := st.chat_input("Apna khayal yahan likhein (e.g., A cinematic sunset over Madinah...)"):
        
        # User message
        st.session_state.messages.append({"role": "user", "content": user_idea})
        with st.chat_message("user"):
            st.markdown(user_idea)

        # Assistant Processing
        with st.chat_message("assistant"):
            
            # A: Generate Prompt
            with st.spinner("तुराब ब्रेन प्रॉम्प्ट तैयार कर रहा है..."):
                manager = PromptLibraryManager()
                enhanced_prompt, category = manager.generate_and_save_prompt(user_idea)
                
            # B: Generate Image
            with st.spinner("AI इमेज बना रहा है..."):
                image_result, successful_model = generate_with_rotation(enhanced_prompt)

                if image_result:
                    # Memory mein save karo aur UI refresh karo
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": "✨ **Success:** AI Prompt generated and locked in the vault. Image successfully created!",
                        "prompt": enhanced_prompt,
                        "image": image_result,
                        "model": successful_model
                    })
                    st.rerun()
                else:
                    error_text = "⚠️ **Error:** Server busy hone ke karan image nahi ban saki."
                    st.error(error_text)
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": error_text,
                        "prompt": enhanced_prompt
                    })

# Execution
if __name__ == "__main__":
    run_image_gen()